install:            # Install requirement as "Environment Setup Section"
- pip install -r docs/requirements.txt
script:             # build sphinx document
- make html
deploy              # deploy to github page
- provider: pages
  skip_cleanup: true
  local_dir: _build/html
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard